apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-pre-helm-hook
  annotations:
    helm.sh/hook: pre-install
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: alpine
          image: alpine:3.19.1
          command: ["sleep", "{{ .Values.delay.preinstall }}"]
      restartPolicy: Never
